[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# /api er shob request sorasori amader api.js function-e pathabe
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200